name: CI
on: 
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

jobs:      
  "tuxOS-Tests":
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ['5.0', '5.1']
    container:
      image: swift:${{ matrix.tag }}
      volumes:
      - $GITHUB_WORKSPACE:/src
      options: --workdir /src
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y zlib1g-dev zip openssl libssl-dev
    - name: Build with debug flags
      run: swift build -c release
    - name: Build with release flags
      run: swift build -c debug

  "macOS-Tests":
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode: ['11.2']
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Show all Xcode versions
      run: ls -an /Applications/ | grep Xcode*
    - name: Change Xcode command line tools
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    - name: Build with debug flags
      run: swift build -c release
    - name: Build with release flags
      run: swift build -c debug
